<?php

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Let's truncate our existing records to start from scratch.
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('products')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('products')->insert([
            [
                'name'              => 'Rau Muống',
                'price'             => 50000,
                'unit'              => 'KG',
                'temp_price'        => 20000,
                'temp_unit'         => 'Gói',
                'temp_weight'       => '400gr',
                'category_id'       => 37,
                'supplier_id'       => 1,
                'short_description' => 'Giòn, ngọt, non',
            ],
            [
                'name'              => 'Rau Lang',
                'price'             => 60000,
                'unit'              => 'KG',
                'temp_price'        => 18000,
                'temp_unit'         => 'Gói',
                'temp_weight'       => '300gr',
                'category_id'       => 37,
                'supplier_id'       => 1,
                'short_description' => 'Mềm, thơm',
            ],
            [
                'name'              => 'Cải Thìa',
                'price'             => 70000,
                'unit'              => 'KG',
                'temp_price'        => 21000,
                'temp_unit'         => 'Gói',
                'temp_weight'       => '300gr',
                'category_id'       => 37,
                'supplier_id'       => 1,
                'short_description' => 'Giòn, Non',
            ],
            [
                'name'              => 'Bồ Ngót',
                'price'             => 15000,
                'unit'              => 'Gói',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 37,
                'supplier_id'       => 2,
                'short_description' => 'Non, thơm',
            ],
            [
                'name'              => 'Dưa Leo',
                'price'             => 30000,
                'unit'              => 'KG',
                'temp_price'        => 15000,
                'temp_unit'         => 'Vỉ',
                'temp_weight'       => '0.5kg',
                'category_id'       => 38,
                'supplier_id'       => 2,
                'short_description' => 'Giòn và ngọt',
            ],
            [
                'name'              => 'Cà Chua',
                'price'             => 60000,
                'unit'              => 'KG',
                'temp_price'        => 6000,
                'temp_unit'         => 'Trái',
                'temp_weight'       => '0.1kg',
                'category_id'       => 38,
                'supplier_id'       => 2,
                'short_description' => 'Chín đỏ, ko dập',
            ],
            [
                'name'              => 'Hành Lá',
                'price'             => 80000,
                'unit'              => 'KG',
                'temp_price'        => 4000,
                'temp_unit'         => 'Nhánh',
                'temp_weight'       => '0.05kg (50gr)',
                'category_id'       => 40,
                'supplier_id'       => 3,
                'short_description' => 'Hành hương miền Trung',
            ],
            [
                'name'              => 'Nấm Rơm',
                'price'             => 24000,
                'unit'              => 'Vỉ',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 39,
                'supplier_id'       => 3,
                'short_description' => '1 vỉ 200gr',
            ],
            [
                'name'              => 'Gà Tre',
                'price'             => 250000,
                'unit'              => 'KG',
                'temp_price'        => 200000,
                'temp_unit'         => 'Con',
                'temp_weight'       => '0.8kg',
                'category_id'       => 28,
                'supplier_id'       => 4,
                'short_description' => 'Thơm ngon',
            ],
            [
                'name'              => 'Gà Nửa Con',
                'price'             => 300000,
                'unit'              => 'KG',
                'temp_price'        => 210000,
                'temp_unit'         => '1/2 Con',
                'temp_weight'       => '0.7kg',
                'category_id'       => 28,
                'supplier_id'       => 4,
                'short_description' => 'Thơm chắc',
            ],
            [
                'name'              => 'Vịt Xiêm',
                'price'             => 180000,
                'unit'              => 'KG',
                'temp_price'        => 360000,
                'temp_unit'         => 'Con',
                'temp_weight'       => '2kg',
                'category_id'       => 28,
                'supplier_id'       => 4,
                'short_description' => 'Ít mỡ',
            ],
            [
                'name'              => 'Ba Chỉ',
                'price'             => 260000,
                'unit'              => 'KG',
                'temp_price'        => 52000,
                'temp_unit'         => 'Miếng',
                'temp_weight'       => '0.2kg',
                'category_id'       => 26,
                'supplier_id'       => 5,
                'short_description' => 'Ít mỡ',
            ],
            [
                'name'              => 'Sườn Non',
                'price'             => 280000,
                'unit'              => 'KG',
                'temp_price'        => 56000,
                'temp_unit'         => 'Vỉ',
                'temp_weight'       => '0.2kg',
                'category_id'       => 26,
                'supplier_id'       => 5,
                'short_description' => 'Nhiều nạc',
            ],
            [
                'name'              => 'Tim',
                'price'             => 180000,
                'unit'              => 'KG',
                'temp_price'        => 90000,
                'temp_unit'         => 'Trái',
                'temp_weight'       => '0.5kg',
                'category_id'       => 26,
                'supplier_id'       => 5,
                'short_description' => 'Nhỏ',
            ],
            [
                'name'              => 'Gạo Nàng Hương',
                'price'             => 52000,
                'unit'              => 'KG',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 41,
                'supplier_id'       => 6,
                'short_description' => 'Thơm mềm',
            ],
            [
                'name'              => 'Gạo Nhật',
                'price'             => 42000,
                'unit'              => 'KG',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 41,
                'supplier_id'       => 6,
                'short_description' => 'Ngọt Cơm',
            ],
            [
                'name'              => 'Nước Mắm',
                'price'             => 52000,
                'unit'              => 'Chai',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 47,
                'supplier_id'       => 7,
                'short_description' => 'Thơm Ngon',
            ],
            [
                'name'              => 'Me Vắt',
                'price'             => 5000,
                'unit'              => 'Vắt',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 40,
                'supplier_id'       => 9,
                'short_description' => 'Me Chín',
            ],
            [
                'name'              => 'Tinh Dầu Dừa',
                'price'             => 250000,
                'unit'              => 'Chai',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 59,
                'supplier_id'       => 9,
                'short_description' => 'Ép Lạnh',
            ],
            [
                'name'              => 'Bột Cám Gạo',
                'price'             => 50000,
                'unit'              => 'Gói',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 60,
                'supplier_id'       => 9,
                'short_description' => 'Nguyên Chất',
            ],
            [
                'name'              => 'Lá Bưởi',
                'price'             => 15000,
                'unit'              => 'Bó',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 61,
                'supplier_id'       => 9,
                'short_description' => 'Lá Khô',
            ],
            [
                'name'              => 'Cây Lăn Tròn',
                'price'             => 40000,
                'unit'              => 'Cây',
                'temp_price'        => NULL,
                'temp_unit'         => NULL,
                'temp_weight'       => NULL,
                'category_id'       => 62,
                'supplier_id'       => 10,
                'short_description' => 'Lưu Thông',
            ],
        ]);
    }
}
